FORMAT: 1A
HOST: http://reststyles.com/api/v1

# REST API for CSS3

API for project REST Styles CSS3

# Group REST-STYLES-CSS3

## About [/]

## Group Users

## Users [/users/login]

### Login of users [POST]

## Users [/users]

### Create users [POST]

## Users [/users/forgot-password]

### Start password recovery - step 1 [POST]

## Users [/users/change-password]

### Change password - step 2 [POST]

## Users [/users]

### Get all users [GET]

## Users [/users/{id_user}]

### Find user [GET]

## Users [/users/{id_user}]

### Edit partial user [PATCH]

## Users [/users/{id_user}]

### Edit user [PUT]

## Users [/users/{id_user}]

### Delete user [DELETE]
